baseURL = "https://mrgf123123.github.io/"
languageCode = "en-us"
title = "江苏明日光伏科技有限公司"
themesDir = "themes"
theme = "hugo-serif-theme"
enableRobotsTXT = true
enableEmoji = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = true  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/android-chrome-512x512.png"
    mobile_height = "48px"
    desktop = "images/logo/android-chrome-512x512.png"
    desktop_height = "48px"
    alt = "明日科技logo"

  [params.seo]
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = '官网 <a class="zerostatic" href="https://mrgf123123.github.io/">https://mrgf123123.github.io/</a>'

[menu]
  # Main Menu
  [[menu.main]]
    name = "产品中心"
    url = "/services/"
      weight = 1

   [[menu.main]]
    #  name = "新闻中心"
    #  url = "/team/"
    # weight = 2

  [[menu.main]]
      name = "关于我们"
      url = "/about/"
      weight = 3

  [[menu.main]]
      name = "联系我们"
      url = "/contact/"
      weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "首页"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "联系我们"
    url = "/contact/"
      weight = 2
